# Generated by Django 6.0.3 on 2026-07-09 04:17
"""
Initial database migration for the restaurant application.

This script creates the database schemas for:
- MenuItem: Products sold
- Order: Transaction records
- Table: Dining tables
- Inventory: Stock tracking
- OrderItem: Single line items in an order
- Reservation: Booking records
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, help_text='Details about ingredients, portion size, and allergy info', verbose_name='Description')),
                ('category', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], max_length=50, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price ($)')),
                ('available', models.BooleanField(default=True, help_text='Designates whether this item can currently be ordered', verbose_name='Is Available')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount ($)')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Served', 'Served'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered At')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(help_text='Unique identifier for the physical table', unique=True, verbose_name='Table Number')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people that can sit at this table', verbose_name='Seating Capacity')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied')], default='Available', help_text='The current occupancy state of the table', max_length=20, verbose_name='Current Status')),
            ],
            options={
                'verbose_name': 'Dining Table',
                'verbose_name_plural': 'Dining Tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Current Quantity in Stock')),
                ('minimum_stock', models.PositiveIntegerField(default=5, help_text='Alert threshold. When quantity falls below this, reordering is required.', verbose_name='Minimum Safety Stock Level')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='restaurant.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'verbose_name': 'Inventory Record',
                'verbose_name_plural': 'Inventory Records',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity Ordered')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal ($)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.menuitem', verbose_name='Menu Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='Parent Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone Number')),
                ('reservation_date', models.DateField(verbose_name='Reservation Date')),
                ('reservation_time', models.TimeField(verbose_name='Reservation Time')),
                ('number_of_people', models.PositiveIntegerField(verbose_name='Number of People')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Reservation Status')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.table', verbose_name='Assigned Table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.table', verbose_name='Table'),
        ),
    ]
